"""delete user-mapping table

Revision ID: 34d82f937037
Revises: 4114a039a9c0
Create Date: 2023-09-24 19:04:39.058291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34d82f937037'
down_revision: Union[str, None] = '4114a039a9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_mapping')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.create_table('test_mapping',
    sa.Column('x', sa.FLOAT(), nullable=True),
    sa.Column('y', sa.FLOAT(), nullable=True),
    sa.Column('delta_y', sa.FLOAT(), nullable=True),
    sa.Column('no_of_ideal_functions', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
